/*
 * CritterViz.java
 *
 * Created on March 12, 2009, 10:37 AM
 */

package org.rlcommunity.critter.plugins;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import org.rlcommunity.critter.Drops.CritterStateDrop;
import org.rlcommunity.critter.Drops.DropInterface;

/**
 *
 * @author  critterbot
 */
public class CritterViz extends JFrame implements WindowListener{
    
    DropInterface di;
    int batState;
    CritterVizLogs logWindow;
    JFrame me;
    private Timer timer;
    private static final int INTERVAL = 100;
    private boolean updated;
    
    /** Creates new form CritterViz */
    public CritterViz(final DropInterface _di) {
        di = _di;
        batState = 0;
        initComponents();
        me = this;
        updated = true;
        
        timer = new javax.swing.Timer(INTERVAL,
                new ActionListener() {

                    public void actionPerformed(ActionEvent e) {
                        if(updated) {
                            repaint();
                            updated = false;
                        }
                    }
                });
        timer.start();
    }
    
    private void showLogWindow() {
        if(logWindow == null)
            javax.swing.SwingUtilities.invokeLater( 
                    new Runnable() {
                        public void run() {
                            logWindow = new CritterVizLogs(di,(WindowListener)me);
                            logWindow.setLocationRelativeTo(me);
                            logWindow.setLocation(me.getWidth(), 0);
                            logWindow.setVisible(true);
                        }
                    }
            );   
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        ir0 = new org.rlcommunity.critter.plugins.RichDisplayBar();
        ir1 = new org.rlcommunity.critter.plugins.RichDisplayBar();
        ir2 = new org.rlcommunity.critter.plugins.RichDisplayBar();
        ir3 = new org.rlcommunity.critter.plugins.RichDisplayBar();
        ir4 = new org.rlcommunity.critter.plugins.RichDisplayBar();
        ir5 = new org.rlcommunity.critter.plugins.RichDisplayBar();
        ir6 = new org.rlcommunity.critter.plugins.RichDisplayBar();
        ir7 = new org.rlcommunity.critter.plugins.RichDisplayBar();
        ir8 = new org.rlcommunity.critter.plugins.RichDisplayBar();
        ir9 = new org.rlcommunity.critter.plugins.RichDisplayBar();
        jPanel4 = new javax.swing.JPanel();
        light0 = new org.rlcommunity.critter.plugins.RichDisplayBar();
        light1 = new org.rlcommunity.critter.plugins.RichDisplayBar();
        light2 = new org.rlcommunity.critter.plugins.RichDisplayBar();
        light3 = new org.rlcommunity.critter.plugins.RichDisplayBar();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        voltage = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        mspeed0 = new org.rlcommunity.critter.plugins.RichDisplayBar();
        mspeed1 = new org.rlcommunity.critter.plugins.RichDisplayBar();
        mspeed2 = new org.rlcommunity.critter.plugins.RichDisplayBar();
        jPanel8 = new javax.swing.JPanel();
        mcurrent0 = new org.rlcommunity.critter.plugins.RichDisplayBar();
        mcurrent1 = new org.rlcommunity.critter.plugins.RichDisplayBar();
        mcurrent2 = new org.rlcommunity.critter.plugins.RichDisplayBar();
        jPanel9 = new javax.swing.JPanel();
        mtemp0 = new org.rlcommunity.critter.plugins.RichDisplayBar(160);
        mtemp1 = new org.rlcommunity.critter.plugins.RichDisplayBar(160);
        mtemp2 = new org.rlcommunity.critter.plugins.RichDisplayBar(160);
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        rotation = new org.rlcommunity.critter.plugins.RichDisplayBar();
        jPanel12 = new javax.swing.JPanel();
        accelx = new org.rlcommunity.critter.plugins.RichDisplayBar();
        accely = new org.rlcommunity.critter.plugins.RichDisplayBar();
        accelz = new org.rlcommunity.critter.plugins.RichDisplayBar();
        jMenuWindow = new javax.swing.JMenuBar();
        jMenuFile = new javax.swing.JMenu();
        jMenuFileExit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuWindowLogs = new javax.swing.JMenuItem();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);
        getContentPane().setLayout(new java.awt.CardLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Critterbot GUI", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("IR Distance Sensors"));
        jPanel3.setLayout(new java.awt.GridLayout());

        ir0.setRange(0, 255);
        ir0.setLayout(new java.awt.GridLayout());
        jPanel3.add(ir0);

        ir1.setRange(0, 255);
        ir1.setLayout(new java.awt.GridLayout());
        jPanel3.add(ir1);

        ir2.setRange(0, 255);
        ir2.setLayout(new java.awt.GridLayout());
        jPanel3.add(ir2);

        ir3.setRange(0, 255);
        ir3.setLayout(new java.awt.GridLayout());
        jPanel3.add(ir3);

        ir4.setRange(0, 255);
        ir4.setLayout(new java.awt.GridLayout());
        jPanel3.add(ir4);

        ir5.setRange(0, 255);
        ir5.setLayout(new java.awt.GridLayout());
        jPanel3.add(ir5);

        ir6.setRange(0, 255);
        ir6.setLayout(new java.awt.GridLayout());
        jPanel3.add(ir6);

        ir7.setRange(0, 255);
        ir7.setLayout(new java.awt.GridLayout());
        jPanel3.add(ir7);

        ir8.setRange(0, 255);
        ir8.setLayout(new java.awt.GridLayout());
        jPanel3.add(ir8);

        ir9.setRange(0, 255);
        ir9.setLayout(new java.awt.GridLayout());
        jPanel3.add(ir9);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Light Sensors"));
        jPanel4.setLayout(new java.awt.GridLayout(1, 0));

        light0.setRange(0, 800);
        light0.setLayout(new java.awt.GridLayout());
        jPanel4.add(light0);

        light1.setRange(0, 800);
        light1.setLayout(new java.awt.GridLayout());
        jPanel4.add(light1);

        light2.setRange(0, 800);
        light2.setLayout(new java.awt.GridLayout());
        jPanel4.add(light2);

        light3.setRange(0, 800);
        light3.setLayout(new java.awt.GridLayout());
        jPanel4.add(light3);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Power"));

        jLabel2.setFont(new java.awt.Font("DejaVu Sans", 0, 18));
        jLabel2.setText("Voltage:");
        jPanel5.add(jLabel2);

        voltage.setColumns(4);
        voltage.setEditable(false);
        voltage.setFont(new java.awt.Font("DejaVu Sans", 0, 18));
        voltage.setText("0.00");
        jPanel5.add(voltage);

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Motors"));
        jPanel6.setLayout(new java.awt.GridLayout(1, 0));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Speed"));
        jPanel2.setLayout(new java.awt.GridLayout(1, 0));

        mspeed0.setRange(-35, 35);
        mspeed0.setLayout(new java.awt.GridLayout());
        jPanel2.add(mspeed0);

        mspeed1.setRange(-35, 35);
        mspeed1.setLayout(new java.awt.GridLayout());
        jPanel2.add(mspeed1);

        mspeed2.setRange(-35, 35);
        mspeed2.setLayout(new java.awt.GridLayout());
        jPanel2.add(mspeed2);

        jPanel6.add(jPanel2);

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("Current"));
        jPanel8.setLayout(new java.awt.GridLayout(1, 0));

        mcurrent0.setRange(0, 90);
        mcurrent0.setLayout(new java.awt.GridLayout());
        jPanel8.add(mcurrent0);

        mcurrent1.setRange(0, 90);
        mcurrent1.setLayout(new java.awt.GridLayout());
        jPanel8.add(mcurrent1);

        mcurrent2.setRange(0, 90);
        mcurrent2.setLayout(new java.awt.GridLayout());
        jPanel8.add(mcurrent2);

        jPanel6.add(jPanel8);

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder("Temperature"));
        jPanel9.setLayout(new java.awt.GridLayout(1, 0));

        mtemp0.setRange(40, 175);

        javax.swing.GroupLayout mtemp0Layout = new javax.swing.GroupLayout(mtemp0);
        mtemp0.setLayout(mtemp0Layout);
        mtemp0Layout.setHorizontalGroup(
            mtemp0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 36, Short.MAX_VALUE)
        );
        mtemp0Layout.setVerticalGroup(
            mtemp0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 178, Short.MAX_VALUE)
        );

        jPanel9.add(mtemp0);

        mtemp1.setRange(40, 175);

        javax.swing.GroupLayout mtemp1Layout = new javax.swing.GroupLayout(mtemp1);
        mtemp1.setLayout(mtemp1Layout);
        mtemp1Layout.setHorizontalGroup(
            mtemp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 36, Short.MAX_VALUE)
        );
        mtemp1Layout.setVerticalGroup(
            mtemp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 178, Short.MAX_VALUE)
        );

        jPanel9.add(mtemp1);

        mtemp2.setRange(40, 175);

        javax.swing.GroupLayout mtemp2Layout = new javax.swing.GroupLayout(mtemp2);
        mtemp2.setLayout(mtemp2Layout);
        mtemp2Layout.setHorizontalGroup(
            mtemp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 36, Short.MAX_VALUE)
        );
        mtemp2Layout.setVerticalGroup(
            mtemp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 178, Short.MAX_VALUE)
        );

        jPanel9.add(mtemp2);

        jPanel6.add(jPanel9);

        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder("Inertial Sensors"));

        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder("Gyroscope"));
        jPanel11.setLayout(new java.awt.GridLayout(1, 0));

        rotation.setRange(-420,420);
        rotation.setLayout(new java.awt.GridLayout());
        jPanel11.add(rotation);

        jPanel12.setBorder(javax.swing.BorderFactory.createTitledBorder("Accelerometer"));
        jPanel12.setLayout(new java.awt.GridLayout(1, 0));

        accelx.setRange(-2048, 2048);
        accelx.setLayout(new java.awt.GridLayout());
        jPanel12.add(accelx);

        accely.setRange(-2048, 2048);
        accely.setLayout(new java.awt.GridLayout());
        jPanel12.add(accely);

        accelz.setRange(-2048, 2048);
        accelz.setLayout(new java.awt.GridLayout());
        jPanel12.add(accelz);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
            .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 374, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 374, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 236, Short.MAX_VALUE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, "card2");

        jMenuFile.setText("File");

        jMenuFileExit.setText("Exit");
        jMenuFileExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuFileExitActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuFileExit);

        jMenuWindow.add(jMenuFile);

        jMenu2.setText("Window");

        jMenuWindowLogs.setText("Logs");
        jMenuWindowLogs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuWindowLogsActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuWindowLogs);

        jMenuWindow.add(jMenu2);

        setJMenuBar(jMenuWindow);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuWindowLogsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuWindowLogsActionPerformed
        showLogWindow();
}//GEN-LAST:event_jMenuWindowLogsActionPerformed

    private void jMenuFileExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuFileExitActionPerformed
        System.exit(0);
}//GEN-LAST:event_jMenuFileExitActionPerformed
    
    public void windowOpened(WindowEvent we) {
        
    }
    public void windowClosed(WindowEvent we) {
        System.out.println("Closing logWindow");
        logWindow = null;
    }
    public void windowClosing(WindowEvent we) {
        
    }
    public void windowIconified(WindowEvent we) {
        
    }
    public void windowDeiconified(WindowEvent we) {
        
    }
    public void windowActivated(WindowEvent we) {
        
    }
    public void windowDeactivated(WindowEvent we) {
        
    }
    
    /**
     * @param args the command line arguments
     */
    /*public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CritterViz().setVisible(true);
            }
        });
    }*/
    
    public synchronized void updateDisplay(CritterStateDrop state) {
        ir0.updateValue(state.ir_distance[0]);
        ir1.updateValue(state.ir_distance[1]);
        ir2.updateValue(state.ir_distance[2]);
        ir3.updateValue(state.ir_distance[3]);
        ir4.updateValue(state.ir_distance[4]);
        ir5.updateValue(state.ir_distance[5]);
        ir6.updateValue(state.ir_distance[6]);
        ir7.updateValue(state.ir_distance[7]);
        ir8.updateValue(state.ir_distance[8]);
        ir9.updateValue(state.ir_distance[9]);
        light0.updateValue(state.light[0]);
        light1.updateValue(state.light[1]);
        light2.updateValue(state.light[2]);
        light3.updateValue(state.light[3]);
        accelx.updateValue(state.accel.x);
        accely.updateValue(state.accel.y);
        accelz.updateValue(state.accel.z);
        rotation.updateValue(state.rotation);
        mspeed0.updateValue(state.motor100.velocity);
        mspeed1.updateValue(state.motor220.velocity);
        mspeed2.updateValue(state.motor340.velocity);
        mcurrent0.updateValue(state.motor100.current);
        mcurrent1.updateValue(state.motor220.current);
        mcurrent2.updateValue(state.motor340.current);
        mtemp0.updateValue(state.motor100.temp);
        mtemp1.updateValue(state.motor220.temp);
        mtemp2.updateValue(state.motor340.temp);
        voltage.setText(Float.toString(((float)state.bus_voltage)/10));
        if(state.bus_voltage < 125) {
            voltage.setBackground(Color.red);
            if(batState < 2) {
                batState = 2;
                JOptionPane.showMessageDialog(this, 
                        "The Critterbot's batteries are critically low.  Turn " +
                        "off the robot NOW!", 
                        "Turn off Critterbot", 
                        JOptionPane.ERROR_MESSAGE);
            }
        }
        else if(state.bus_voltage < 135) {
            voltage.setBackground(Color.red);
            if(batState < 1) {
                batState = 1;
                JOptionPane.showMessageDialog(this, 
                        "The Critterbot's batteries are running low.", 
                        "Low Battery", 
                        JOptionPane.WARNING_MESSAGE);
            }
        }
        else
            voltage.setBackground(Color.white);
        updated = true;
        if(logWindow != null)
            logWindow.updateTime(state.time.getTimeInMillis());
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.rlcommunity.critter.plugins.RichDisplayBar accelx;
    private org.rlcommunity.critter.plugins.RichDisplayBar accely;
    private org.rlcommunity.critter.plugins.RichDisplayBar accelz;
    private org.rlcommunity.critter.plugins.RichDisplayBar ir0;
    private org.rlcommunity.critter.plugins.RichDisplayBar ir1;
    private org.rlcommunity.critter.plugins.RichDisplayBar ir2;
    private org.rlcommunity.critter.plugins.RichDisplayBar ir3;
    private org.rlcommunity.critter.plugins.RichDisplayBar ir4;
    private org.rlcommunity.critter.plugins.RichDisplayBar ir5;
    private org.rlcommunity.critter.plugins.RichDisplayBar ir6;
    private org.rlcommunity.critter.plugins.RichDisplayBar ir7;
    private org.rlcommunity.critter.plugins.RichDisplayBar ir8;
    private org.rlcommunity.critter.plugins.RichDisplayBar ir9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenuFile;
    private javax.swing.JMenuItem jMenuFileExit;
    private javax.swing.JMenuBar jMenuWindow;
    private javax.swing.JMenuItem jMenuWindowLogs;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private org.rlcommunity.critter.plugins.RichDisplayBar light0;
    private org.rlcommunity.critter.plugins.RichDisplayBar light1;
    private org.rlcommunity.critter.plugins.RichDisplayBar light2;
    private org.rlcommunity.critter.plugins.RichDisplayBar light3;
    private org.rlcommunity.critter.plugins.RichDisplayBar mcurrent0;
    private org.rlcommunity.critter.plugins.RichDisplayBar mcurrent1;
    private org.rlcommunity.critter.plugins.RichDisplayBar mcurrent2;
    private org.rlcommunity.critter.plugins.RichDisplayBar mspeed0;
    private org.rlcommunity.critter.plugins.RichDisplayBar mspeed1;
    private org.rlcommunity.critter.plugins.RichDisplayBar mspeed2;
    private org.rlcommunity.critter.plugins.RichDisplayBar mtemp0;
    private org.rlcommunity.critter.plugins.RichDisplayBar mtemp1;
    private org.rlcommunity.critter.plugins.RichDisplayBar mtemp2;
    private org.rlcommunity.critter.plugins.RichDisplayBar rotation;
    private javax.swing.JTextField voltage;
    // End of variables declaration//GEN-END:variables
    
}
