/*
 * CritterVizLogs.java
 *
 * Created on March 25, 2009, 11:54 AM
 */

package org.rlcommunity.critter.visualizer;

import java.awt.event.WindowListener;
import java.util.Calendar;
import java.util.SimpleTimeZone;
import java.util.TimeZone;
import org.rlcommunity.critter.Drops.CritterLogTagDrop;
import org.rlcommunity.critter.Drops.DropInterface;

/**
 *
 * @author  critterbot
 */
public class CritterVizLogs extends javax.swing.JFrame {
    
    DropInterface di;
    WindowListener mainViz;
    /** Creates new form CritterVizLogs */
    public CritterVizLogs(DropInterface _di,WindowListener _mainViz) {
        di = _di;
        mainViz = _mainViz;
        initComponents();
        this.addWindowListener(mainViz);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLogComment = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLogCommentSend = new javax.swing.JButton();
        jLogName = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jSecond = new javax.swing.JTextField();
        jMinute = new javax.swing.JTextField();
        jHour = new javax.swing.JTextField();
        jYear = new javax.swing.JTextField();
        jMonth = new javax.swing.JTextField();
        jDay = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Log Interface");
        setLocationByPlatform(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Log Comments"));
        jPanel1.setPreferredSize(new java.awt.Dimension(439, 339));

        jLogComment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendLogTag(evt);
            }
        });

        jLabel2.setLabelFor(jLogName);
        jLabel2.setText("Name:");

        jLogCommentSend.setText("Send");
        jLogCommentSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendLogTag(evt);
            }
        });

        jLogName.setEditable(true);
        jLogName.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "sokolsky", "anna", "degris", "sutton", "wiewiora", "awhite" }));
        jLogName.setSelectedItem(System.getProperty("user.name"));
        jLogName.setVerifyInputWhenFocusTarget(false);

        jLabel1.setLabelFor(jLogComment);
        jLabel1.setText("Comment:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLogName, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLogComment, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLogCommentSend)
                .addGap(20, 20, 20))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLogName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLogComment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLogCommentSend)))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Time"));

        jSecond.setEditable(false);
        jSecond.setText("00");
        jSecond.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSecondActionPerformed(evt);
            }
        });

        jMinute.setEditable(false);
        jMinute.setText("00");
        jMinute.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMinuteActionPerformed(evt);
            }
        });

        jHour.setEditable(false);
        jHour.setText("00");
        jHour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jHourActionPerformed(evt);
            }
        });

        jYear.setEditable(false);
        jYear.setText("1970");
        jYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jYearActionPerformed(evt);
            }
        });

        jMonth.setEditable(false);
        jMonth.setText("1");
        jMonth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMonthActionPerformed(evt);
            }
        });

        jDay.setEditable(false);
        jDay.setText("1");
        jDay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDayActionPerformed(evt);
            }
        });

        jLabel3.setText(":");

        jLabel4.setText(":");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(52, Short.MAX_VALUE)
                .addComponent(jYear, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDay, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jHour, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jLabel3)
                .addGap(4, 4, 4)
                .addComponent(jMinute, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jLabel4)
                .addGap(4, 4, 4)
                .addComponent(jSecond, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jMinute, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jHour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jSecond, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 407, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sendLogTag(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendLogTag
        di.sendDrop(new CritterLogTagDrop(jLogName.getSelectedItem().toString(),
                jLogComment.getText()));
        jLogComment.setText("");
    }//GEN-LAST:event_sendLogTag

    private void jYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jYearActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jYearActionPerformed

    private void jMonthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMonthActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jMonthActionPerformed

    private void jDayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDayActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jDayActionPerformed

    private void jHourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jHourActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jHourActionPerformed

    private void jMinuteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMinuteActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jMinuteActionPerformed

    private void jSecondActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSecondActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jSecondActionPerformed
 
 
    private static String getUserName() {
        return System.getProperty("user.name");
    }
    
    public synchronized void updateTime(long time) {
        Calendar cal = Calendar.getInstance();
        //cal.setTimeZone(TimeZone.getTimeZone("MST"));
        cal.setTimeInMillis(time);
        if(Integer.parseInt(jSecond.getText()) != cal.get(Calendar.SECOND)) {
            jYear.setText(Integer.toString(cal.get(Calendar.YEAR)));
            jMonth.setText(Integer.toString(cal.get(Calendar.MONTH) + 1));
            jDay.setText(Integer.toString(cal.get(Calendar.DAY_OF_MONTH)));
            jHour.setText(Integer.toString(cal.get(Calendar.HOUR_OF_DAY)));
            jMinute.setText(Integer.toString(cal.get(Calendar.MINUTE))); 
            jSecond.setText(Integer.toString(cal.get(Calendar.SECOND)));
            repaint();
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField jDay;
    private javax.swing.JTextField jHour;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jLogComment;
    private javax.swing.JButton jLogCommentSend;
    private javax.swing.JComboBox jLogName;
    private javax.swing.JTextField jMinute;
    private javax.swing.JTextField jMonth;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jSecond;
    private javax.swing.JTextField jYear;
    // End of variables declaration//GEN-END:variables
    
}
