package org.rlcommunity.critter;

/**
  * Collision
  *
  * This class encapsulates collision information, in particular where
  *  the two colliding objects meet in space.
  *
  * @author Marc G. Bellemare
  */

public class Collision
{
    public Collision(Collision pCol) {
        this.normal = new Vector2D(pCol.normal);
        this.point = new Vector2D(pCol.point);
        this.magnitude = pCol.magnitude;
        this.alpha = pCol.alpha;
        this.beta = pCol.beta;
    }

    public Collision() {
    }
    
    /** The normal to the collision, pointing away from the first object */
    public Vector2D normal;
    /** The point of collision */
    public Vector2D point;
    /** The magnitude of the force generated by this collision */
    public double magnitude;
    /** The point of collision, in polygon-coordinates, for each polygon
     *   involved */
    public double alpha,  beta;
}
