/*
 * Copyright 2008 Brian Tanner
 * http://bt-recordbook.googlecode.com/
 * brian@tannerpages.com
 * http://brian.tannerpages.com
 * 
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 * 
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
package org.rlcommunity.critter.Clients;

import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import org.rlcommunity.critter.Drops.*;

import java.util.List;
import java.util.LinkedList;

/**
 *
 * @author Brian Tanner
 * @author Marc G. Bellemare
 */
public class KeyboardClient implements DropClient, KeyListener {

    private int up, down;
    private int left, right;
    private int slideleft, slideright;
    
    private int motor100;
    private int motor220;
    private int motor340;

    public boolean hasChange;

    public KeyboardClient() {
        up = down = left = right = 0;
        slideleft = slideright = 0;
        motor100 = motor220 = motor340 = 0;
        hasChange = false;
    }

    public void keyTyped(KeyEvent e) {
    }

    public void keyPressed(KeyEvent e) {
        hasChange = true;

        switch (e.getKeyCode()) {
          case KeyEvent.VK_UP:
          case KeyEvent.VK_W:
            up = 1;
            break;
          case KeyEvent.VK_DOWN:
          case KeyEvent.VK_S:
            down = 1;
            break;
          case KeyEvent.VK_LEFT:
          case KeyEvent.VK_A:
            left = 1;
            break;
          case KeyEvent.VK_RIGHT:
          case KeyEvent.VK_D:
            right = 1;
            break;
          case KeyEvent.VK_Q:
            slideleft = 1;
            break;
          case KeyEvent.VK_E:
            slideright = 1;
            break;
          case KeyEvent.VK_U:
            motor100 = 1;
            break;
          case KeyEvent.VK_I:
            motor220 = 1;
            break;
          case KeyEvent.VK_O:
            motor340 = 1;
            break;
        }
    }

    public void keyReleased(KeyEvent e) {
        hasChange = true;

        switch (e.getKeyCode()) {
          case KeyEvent.VK_UP:
          case KeyEvent.VK_W:
            up = 0;
            break;
          case KeyEvent.VK_DOWN:
          case KeyEvent.VK_S:
            down = 0;
            break;
          case KeyEvent.VK_LEFT:
          case KeyEvent.VK_A:
            left = 0;
            break;
          case KeyEvent.VK_RIGHT:
          case KeyEvent.VK_D:
            right = 0;
            break;
          case KeyEvent.VK_Q:
            slideleft = 0;
            break;
          case KeyEvent.VK_E:
            slideright = 0;
            break;
          case KeyEvent.VK_U:
            motor100 = 0;
            break;
          case KeyEvent.VK_I:
            motor220 = 0;
            break;
          case KeyEvent.VK_O:
            motor340 = 0;
            break;
        }
    }


    long lastDropTime=System.currentTimeMillis();
    long keyboardDropInterval=50;
    /**
     * This might be setting velocity to 0 when no command received.
     *
     * @return A control drop (encapsulated in a list) generated by the client
     */
    public List<SimulatorDrop> receive() {
        LinkedList<SimulatorDrop> dropList = new LinkedList<SimulatorDrop>();
        // Produce a drop iff: a key is pressed, or was released, and enough
        // time has elapsed
        if (!hasChange
                && System.currentTimeMillis() - lastDropTime < keyboardDropInterval) {
            return dropList;
        }

        CritterControlDrop controlDrop = new CritterControlDrop();

        // We need to consider keypresses as 'changes' as keyPressed stops being
        //  called after we release one of the keys (e.g. going forward and left
        //  causes the robot to stop when left is released).
        hasChange = hasChange || (up > 0 || down > 0 || left > 0 || right > 0 ||
                motor100 > 0 || motor220 > 0 || motor340 > 0 || slideleft > 0 ||
                slideright > 0);
        
        if (hasChange) {
            if (up > 0 || down > 0 || right > 0 || left > 0 ||
                     slideleft > 0 || slideright > 0) {
                setDropWithXYThetaSpace(controlDrop);
            } else if (motor100 > 0 || motor220 > 0 || motor340 > 0) {
                setDropWithMotorSpace(controlDrop);
            }
            else // Send a zero drop (it MUST be sent)
                setDropWithXYThetaSpace(controlDrop);
        }
        hasChange = false;
        dropList.add(controlDrop);
        lastDropTime = System.currentTimeMillis();
        return dropList;
    }

    private void setDropWithMotorSpace(CritterControlDrop controlDrop) {
        controlDrop.motor_mode = CritterControlDrop.MotorMode.WHEEL_SPACE;

        int maxVel = 100;

        controlDrop.m100_vel = motor100 * maxVel;
        controlDrop.m220_vel = motor220 * maxVel;
        controlDrop.m340_vel = motor340 * maxVel;
    }

    private void setDropWithXYThetaSpace(CritterControlDrop controlDrop) {
        double velocityX, velocityY, angVel;
        int maxVel = 100; // 100 cm/s
        int maxAngularVel = 27; // Roughly 1/2 a turn in a second
        velocityX = (up * maxVel - down * maxVel);
        velocityY = (slideright * maxVel - slideleft * maxVel);
        // @todo MGB: The angle here LOOKS wrong (right is positive). The idea
        //  is that the world is drawn inverted around the x axis, resulting in
        //  a left turn looking like a right turn.
        angVel = (right * maxAngularVel + left * -maxAngularVel);
        controlDrop.motor_mode = CritterControlDrop.MotorMode.XYTHETA_SPACE;
        controlDrop.x_vel = (int) velocityX;
        controlDrop.y_vel = (int) velocityY;
        controlDrop.theta_vel = (int) angVel;
    }

    public void send(SimulatorDrop pData) {
      // Do nothing - the keyboard client has no 'output' per se
    }
}
