/*
 * CritterViz.java
 *
 * Created on March 12, 2009, 10:37 AM
 */

package org.rlcommunity.critter.plugins;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import javax.swing.JFrame;
import javax.swing.Timer;
import org.rlcommunity.critter.Drops.CritterStateDrop;
import org.rlcommunity.critter.SimulatorDrawWorld;

/**
 *
 * @author  critterbot
 */
public class CritterbotVisualizerFrame extends JFrame implements WindowListener{
    
    int batState;
    CritterVizLogs logWindow;
    JFrame me;
    private Timer timer;
    private static final int INTERVAL = 100;
    private boolean updated;

    private final Object aUpdateSemaphore = new Object();
    
    /** Creates new form CritterViz */
    public CritterbotVisualizerFrame() {
        setLocation(SimulatorDrawWorld.x_size+5, 0);
        batState = 0;
        initComponents();
        me = this;
        updated = true;
        
        timer = new javax.swing.Timer(INTERVAL,
                new ActionListener() {

                    public void actionPerformed(ActionEvent e) {
                        synchronized(aUpdateSemaphore) {
                          if(updated) {
                            repaint();
                            updated = false;
                          }
                        }
                    }
                });
        timer.start();
    }
    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        ir0 = new org.rlcommunity.critter.plugins.RichDisplayBar();
        ir1 = new org.rlcommunity.critter.plugins.RichDisplayBar();
        ir2 = new org.rlcommunity.critter.plugins.RichDisplayBar();
        ir3 = new org.rlcommunity.critter.plugins.RichDisplayBar();
        ir4 = new org.rlcommunity.critter.plugins.RichDisplayBar();
        ir5 = new org.rlcommunity.critter.plugins.RichDisplayBar();
        ir6 = new org.rlcommunity.critter.plugins.RichDisplayBar();
        ir7 = new org.rlcommunity.critter.plugins.RichDisplayBar();
        ir8 = new org.rlcommunity.critter.plugins.RichDisplayBar();
        ir9 = new org.rlcommunity.critter.plugins.RichDisplayBar();
        jPanel4 = new javax.swing.JPanel();
        light0 = new org.rlcommunity.critter.plugins.RichDisplayBar();
        light1 = new org.rlcommunity.critter.plugins.RichDisplayBar();
        light2 = new org.rlcommunity.critter.plugins.RichDisplayBar();
        light3 = new org.rlcommunity.critter.plugins.RichDisplayBar();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        voltage = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        mspeed0 = new org.rlcommunity.critter.plugins.RichDisplayBar();
        mspeed1 = new org.rlcommunity.critter.plugins.RichDisplayBar();
        mspeed2 = new org.rlcommunity.critter.plugins.RichDisplayBar();
        jPanel8 = new javax.swing.JPanel();
        mcurrent0 = new org.rlcommunity.critter.plugins.RichDisplayBar();
        mcurrent1 = new org.rlcommunity.critter.plugins.RichDisplayBar();
        mcurrent2 = new org.rlcommunity.critter.plugins.RichDisplayBar();
        jPanel9 = new javax.swing.JPanel();
        mtemp0 = new org.rlcommunity.critter.plugins.RichDisplayBar(160);
        mtemp1 = new org.rlcommunity.critter.plugins.RichDisplayBar(160);
        mtemp2 = new org.rlcommunity.critter.plugins.RichDisplayBar(160);
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        rotation = new org.rlcommunity.critter.plugins.RichDisplayBar();
        jPanel12 = new javax.swing.JPanel();
        accelx = new org.rlcommunity.critter.plugins.RichDisplayBar();
        accely = new org.rlcommunity.critter.plugins.RichDisplayBar();
        accelz = new org.rlcommunity.critter.plugins.RichDisplayBar();
        jPanel13 = new javax.swing.JPanel();
        jMenuWindow = new javax.swing.JMenuBar();
        jMenuFile = new javax.swing.JMenu();
        jMenuFileExit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuWindowLogs = new javax.swing.JMenuItem();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Critterbot GUI", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("IR Distance Sensors"));
        jPanel3.setLayout(new java.awt.GridLayout(1, 0));

        ir0.setRange(0, 255);

        javax.swing.GroupLayout ir0Layout = new javax.swing.GroupLayout(ir0);
        ir0.setLayout(ir0Layout);
        ir0Layout.setHorizontalGroup(
            ir0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 26, Short.MAX_VALUE)
        );
        ir0Layout.setVerticalGroup(
            ir0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 299, Short.MAX_VALUE)
        );

        jPanel3.add(ir0);

        ir1.setRange(0, 255);

        javax.swing.GroupLayout ir1Layout = new javax.swing.GroupLayout(ir1);
        ir1.setLayout(ir1Layout);
        ir1Layout.setHorizontalGroup(
            ir1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 26, Short.MAX_VALUE)
        );
        ir1Layout.setVerticalGroup(
            ir1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 299, Short.MAX_VALUE)
        );

        jPanel3.add(ir1);

        ir2.setRange(0, 255);

        javax.swing.GroupLayout ir2Layout = new javax.swing.GroupLayout(ir2);
        ir2.setLayout(ir2Layout);
        ir2Layout.setHorizontalGroup(
            ir2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 26, Short.MAX_VALUE)
        );
        ir2Layout.setVerticalGroup(
            ir2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 299, Short.MAX_VALUE)
        );

        jPanel3.add(ir2);

        ir3.setRange(0, 255);

        javax.swing.GroupLayout ir3Layout = new javax.swing.GroupLayout(ir3);
        ir3.setLayout(ir3Layout);
        ir3Layout.setHorizontalGroup(
            ir3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 26, Short.MAX_VALUE)
        );
        ir3Layout.setVerticalGroup(
            ir3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 299, Short.MAX_VALUE)
        );

        jPanel3.add(ir3);

        ir4.setRange(0, 255);

        javax.swing.GroupLayout ir4Layout = new javax.swing.GroupLayout(ir4);
        ir4.setLayout(ir4Layout);
        ir4Layout.setHorizontalGroup(
            ir4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 26, Short.MAX_VALUE)
        );
        ir4Layout.setVerticalGroup(
            ir4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 299, Short.MAX_VALUE)
        );

        jPanel3.add(ir4);

        ir5.setRange(0, 255);

        javax.swing.GroupLayout ir5Layout = new javax.swing.GroupLayout(ir5);
        ir5.setLayout(ir5Layout);
        ir5Layout.setHorizontalGroup(
            ir5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 26, Short.MAX_VALUE)
        );
        ir5Layout.setVerticalGroup(
            ir5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 299, Short.MAX_VALUE)
        );

        jPanel3.add(ir5);

        ir6.setRange(0, 255);

        javax.swing.GroupLayout ir6Layout = new javax.swing.GroupLayout(ir6);
        ir6.setLayout(ir6Layout);
        ir6Layout.setHorizontalGroup(
            ir6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 26, Short.MAX_VALUE)
        );
        ir6Layout.setVerticalGroup(
            ir6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 299, Short.MAX_VALUE)
        );

        jPanel3.add(ir6);

        ir7.setRange(0, 255);

        javax.swing.GroupLayout ir7Layout = new javax.swing.GroupLayout(ir7);
        ir7.setLayout(ir7Layout);
        ir7Layout.setHorizontalGroup(
            ir7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 26, Short.MAX_VALUE)
        );
        ir7Layout.setVerticalGroup(
            ir7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 299, Short.MAX_VALUE)
        );

        jPanel3.add(ir7);

        ir8.setRange(0, 255);

        javax.swing.GroupLayout ir8Layout = new javax.swing.GroupLayout(ir8);
        ir8.setLayout(ir8Layout);
        ir8Layout.setHorizontalGroup(
            ir8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 26, Short.MAX_VALUE)
        );
        ir8Layout.setVerticalGroup(
            ir8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 299, Short.MAX_VALUE)
        );

        jPanel3.add(ir8);

        ir9.setRange(0, 255);

        javax.swing.GroupLayout ir9Layout = new javax.swing.GroupLayout(ir9);
        ir9.setLayout(ir9Layout);
        ir9Layout.setHorizontalGroup(
            ir9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 26, Short.MAX_VALUE)
        );
        ir9Layout.setVerticalGroup(
            ir9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 299, Short.MAX_VALUE)
        );

        jPanel3.add(ir9);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Light Sensors"));
        jPanel4.setLayout(new java.awt.GridLayout(1, 0));

        light0.setRange(0, 800);

        javax.swing.GroupLayout light0Layout = new javax.swing.GroupLayout(light0);
        light0.setLayout(light0Layout);
        light0Layout.setHorizontalGroup(
            light0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 27, Short.MAX_VALUE)
        );
        light0Layout.setVerticalGroup(
            light0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 299, Short.MAX_VALUE)
        );

        jPanel4.add(light0);

        light1.setRange(0, 800);

        javax.swing.GroupLayout light1Layout = new javax.swing.GroupLayout(light1);
        light1.setLayout(light1Layout);
        light1Layout.setHorizontalGroup(
            light1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 27, Short.MAX_VALUE)
        );
        light1Layout.setVerticalGroup(
            light1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 299, Short.MAX_VALUE)
        );

        jPanel4.add(light1);

        light2.setRange(0, 800);

        javax.swing.GroupLayout light2Layout = new javax.swing.GroupLayout(light2);
        light2.setLayout(light2Layout);
        light2Layout.setHorizontalGroup(
            light2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 27, Short.MAX_VALUE)
        );
        light2Layout.setVerticalGroup(
            light2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 299, Short.MAX_VALUE)
        );

        jPanel4.add(light2);

        light3.setRange(0, 800);

        javax.swing.GroupLayout light3Layout = new javax.swing.GroupLayout(light3);
        light3.setLayout(light3Layout);
        light3Layout.setHorizontalGroup(
            light3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 27, Short.MAX_VALUE)
        );
        light3Layout.setVerticalGroup(
            light3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 299, Short.MAX_VALUE)
        );

        jPanel4.add(light3);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Power"));

        jLabel2.setFont(new java.awt.Font("DejaVu Sans", 0, 18));
        jLabel2.setText("Voltage:");
        jPanel5.add(jLabel2);

        voltage.setColumns(4);
        voltage.setEditable(false);
        voltage.setFont(new java.awt.Font("DejaVu Sans", 0, 18));
        voltage.setText("0.00");
        jPanel5.add(voltage);

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Motors"));
        jPanel6.setLayout(new java.awt.GridLayout(1, 0));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Speed"));
        jPanel2.setLayout(new java.awt.GridLayout(1, 0));

        mspeed0.setRange(-35, 35);

        javax.swing.GroupLayout mspeed0Layout = new javax.swing.GroupLayout(mspeed0);
        mspeed0.setLayout(mspeed0Layout);
        mspeed0Layout.setHorizontalGroup(
            mspeed0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 39, Short.MAX_VALUE)
        );
        mspeed0Layout.setVerticalGroup(
            mspeed0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 188, Short.MAX_VALUE)
        );

        jPanel2.add(mspeed0);

        mspeed1.setRange(-35, 35);

        javax.swing.GroupLayout mspeed1Layout = new javax.swing.GroupLayout(mspeed1);
        mspeed1.setLayout(mspeed1Layout);
        mspeed1Layout.setHorizontalGroup(
            mspeed1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 39, Short.MAX_VALUE)
        );
        mspeed1Layout.setVerticalGroup(
            mspeed1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 188, Short.MAX_VALUE)
        );

        jPanel2.add(mspeed1);

        mspeed2.setRange(-35, 35);

        javax.swing.GroupLayout mspeed2Layout = new javax.swing.GroupLayout(mspeed2);
        mspeed2.setLayout(mspeed2Layout);
        mspeed2Layout.setHorizontalGroup(
            mspeed2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 39, Short.MAX_VALUE)
        );
        mspeed2Layout.setVerticalGroup(
            mspeed2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 188, Short.MAX_VALUE)
        );

        jPanel2.add(mspeed2);

        jPanel6.add(jPanel2);

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("Current"));
        jPanel8.setLayout(new java.awt.GridLayout(1, 0));

        mcurrent0.setRange(0, 90);

        javax.swing.GroupLayout mcurrent0Layout = new javax.swing.GroupLayout(mcurrent0);
        mcurrent0.setLayout(mcurrent0Layout);
        mcurrent0Layout.setHorizontalGroup(
            mcurrent0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 39, Short.MAX_VALUE)
        );
        mcurrent0Layout.setVerticalGroup(
            mcurrent0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 188, Short.MAX_VALUE)
        );

        jPanel8.add(mcurrent0);

        mcurrent1.setRange(0, 90);

        javax.swing.GroupLayout mcurrent1Layout = new javax.swing.GroupLayout(mcurrent1);
        mcurrent1.setLayout(mcurrent1Layout);
        mcurrent1Layout.setHorizontalGroup(
            mcurrent1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 39, Short.MAX_VALUE)
        );
        mcurrent1Layout.setVerticalGroup(
            mcurrent1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 188, Short.MAX_VALUE)
        );

        jPanel8.add(mcurrent1);

        mcurrent2.setRange(0, 90);

        javax.swing.GroupLayout mcurrent2Layout = new javax.swing.GroupLayout(mcurrent2);
        mcurrent2.setLayout(mcurrent2Layout);
        mcurrent2Layout.setHorizontalGroup(
            mcurrent2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 39, Short.MAX_VALUE)
        );
        mcurrent2Layout.setVerticalGroup(
            mcurrent2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 188, Short.MAX_VALUE)
        );

        jPanel8.add(mcurrent2);

        jPanel6.add(jPanel8);

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder("Temperature"));
        jPanel9.setLayout(new java.awt.GridLayout(1, 0));

        mtemp0.setRange(40, 175);

        javax.swing.GroupLayout mtemp0Layout = new javax.swing.GroupLayout(mtemp0);
        mtemp0.setLayout(mtemp0Layout);
        mtemp0Layout.setHorizontalGroup(
            mtemp0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 39, Short.MAX_VALUE)
        );
        mtemp0Layout.setVerticalGroup(
            mtemp0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 188, Short.MAX_VALUE)
        );

        jPanel9.add(mtemp0);

        mtemp1.setRange(40, 175);

        javax.swing.GroupLayout mtemp1Layout = new javax.swing.GroupLayout(mtemp1);
        mtemp1.setLayout(mtemp1Layout);
        mtemp1Layout.setHorizontalGroup(
            mtemp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 39, Short.MAX_VALUE)
        );
        mtemp1Layout.setVerticalGroup(
            mtemp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 188, Short.MAX_VALUE)
        );

        jPanel9.add(mtemp1);

        mtemp2.setRange(40, 175);

        javax.swing.GroupLayout mtemp2Layout = new javax.swing.GroupLayout(mtemp2);
        mtemp2.setLayout(mtemp2Layout);
        mtemp2Layout.setHorizontalGroup(
            mtemp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 39, Short.MAX_VALUE)
        );
        mtemp2Layout.setVerticalGroup(
            mtemp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 188, Short.MAX_VALUE)
        );

        jPanel9.add(mtemp2);

        jPanel6.add(jPanel9);

        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder("Inertial Sensors"));

        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder("Gyroscope"));
        jPanel11.setLayout(new java.awt.GridLayout(1, 0));

        rotation.setRange(-420,420);

        javax.swing.GroupLayout rotationLayout = new javax.swing.GroupLayout(rotation);
        rotation.setLayout(rotationLayout);
        rotationLayout.setHorizontalGroup(
            rotationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );
        rotationLayout.setVerticalGroup(
            rotationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 185, Short.MAX_VALUE)
        );

        jPanel11.add(rotation);

        jPanel12.setBorder(javax.swing.BorderFactory.createTitledBorder("Accelerometer"));
        jPanel12.setLayout(new java.awt.GridLayout(1, 0));

        accelx.setRange(-2048, 2048);

        javax.swing.GroupLayout accelxLayout = new javax.swing.GroupLayout(accelx);
        accelx.setLayout(accelxLayout);
        accelxLayout.setHorizontalGroup(
            accelxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 33, Short.MAX_VALUE)
        );
        accelxLayout.setVerticalGroup(
            accelxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 185, Short.MAX_VALUE)
        );

        jPanel12.add(accelx);

        accely.setRange(-2048, 2048);

        javax.swing.GroupLayout accelyLayout = new javax.swing.GroupLayout(accely);
        accely.setLayout(accelyLayout);
        accelyLayout.setHorizontalGroup(
            accelyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 33, Short.MAX_VALUE)
        );
        accelyLayout.setVerticalGroup(
            accelyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 185, Short.MAX_VALUE)
        );

        jPanel12.add(accely);

        accelz.setRange(-2048, 2048);

        javax.swing.GroupLayout accelzLayout = new javax.swing.GroupLayout(accelz);
        accelz.setLayout(accelzLayout);
        accelzLayout.setHorizontalGroup(
            accelzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 33, Short.MAX_VALUE)
        );
        accelzLayout.setVerticalGroup(
            accelzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 185, Short.MAX_VALUE)
        );

        jPanel12.add(accelz);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel11, 0, 214, Short.MAX_VALUE)
                    .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel13.setBorder(javax.swing.BorderFactory.createTitledBorder("Other"));

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 213, Short.MAX_VALUE)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 217, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel6, 0, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                    .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel4, 0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 246, Short.MAX_VALUE)
                    .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jMenuFile.setText("File");

        jMenuFileExit.setText("Exit");
        jMenuFileExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuFileExitActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuFileExit);

        jMenuWindow.add(jMenuFile);

        jMenu2.setText("Window");

        jMenuWindowLogs.setText("Logs");
        jMenuWindowLogs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuWindowLogsActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuWindowLogs);

        jMenuWindow.add(jMenu2);

        setJMenuBar(jMenuWindow);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 617, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuWindowLogsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuWindowLogsActionPerformed
}//GEN-LAST:event_jMenuWindowLogsActionPerformed

    private void jMenuFileExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuFileExitActionPerformed
        System.exit(0);
}//GEN-LAST:event_jMenuFileExitActionPerformed
    
    public void windowOpened(WindowEvent we) {
        
    }
    public void windowClosed(WindowEvent we) {
    }
    public void windowClosing(WindowEvent we) {
        
    }
    public void windowIconified(WindowEvent we) {
        
    }
    public void windowDeiconified(WindowEvent we) {
        
    }
    public void windowActivated(WindowEvent we) {
        
    }
    public void windowDeactivated(WindowEvent we) {
        
    }
    
    /**
     * @param args the command line arguments
     */
    /*public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CritterViz().setVisible(true);
            }
        });
    }*/
    
    public void updateDisplay(CritterStateDrop state) {
      synchronized(aUpdateSemaphore) {
        ir0.updateValue(state.ir_distance[0]);
        ir1.updateValue(state.ir_distance[1]);
        ir2.updateValue(state.ir_distance[2]);
        ir3.updateValue(state.ir_distance[3]);
        ir4.updateValue(state.ir_distance[4]);
        ir5.updateValue(state.ir_distance[5]);
        ir6.updateValue(state.ir_distance[6]);
        ir7.updateValue(state.ir_distance[7]);
        ir8.updateValue(state.ir_distance[8]);
        ir9.updateValue(state.ir_distance[9]);
        light0.updateValue(state.light[0]);
        light1.updateValue(state.light[1]);
        light2.updateValue(state.light[2]);
        light3.updateValue(state.light[3]);
        accelx.updateValue(state.accel.x);
        accely.updateValue(state.accel.y);
        accelz.updateValue(state.accel.z);
        rotation.updateValue(state.rotation);
        mspeed0.updateValue(state.motor100.velocity);
        mspeed1.updateValue(state.motor220.velocity);
        mspeed2.updateValue(state.motor340.velocity);
        mcurrent0.updateValue(state.motor100.current);
        mcurrent1.updateValue(state.motor220.current);
        mcurrent2.updateValue(state.motor340.current);
        mtemp0.updateValue(state.motor100.temp);
        mtemp1.updateValue(state.motor220.temp);
        mtemp2.updateValue(state.motor340.temp);
        voltage.setText(Float.toString(((float)state.bus_voltage)/10));
        voltage.setBackground(Color.white);
        updated = true;
      }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.rlcommunity.critter.plugins.RichDisplayBar accelx;
    private org.rlcommunity.critter.plugins.RichDisplayBar accely;
    private org.rlcommunity.critter.plugins.RichDisplayBar accelz;
    private org.rlcommunity.critter.plugins.RichDisplayBar ir0;
    private org.rlcommunity.critter.plugins.RichDisplayBar ir1;
    private org.rlcommunity.critter.plugins.RichDisplayBar ir2;
    private org.rlcommunity.critter.plugins.RichDisplayBar ir3;
    private org.rlcommunity.critter.plugins.RichDisplayBar ir4;
    private org.rlcommunity.critter.plugins.RichDisplayBar ir5;
    private org.rlcommunity.critter.plugins.RichDisplayBar ir6;
    private org.rlcommunity.critter.plugins.RichDisplayBar ir7;
    private org.rlcommunity.critter.plugins.RichDisplayBar ir8;
    private org.rlcommunity.critter.plugins.RichDisplayBar ir9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenuFile;
    private javax.swing.JMenuItem jMenuFileExit;
    private javax.swing.JMenuBar jMenuWindow;
    private javax.swing.JMenuItem jMenuWindowLogs;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private org.rlcommunity.critter.plugins.RichDisplayBar light0;
    private org.rlcommunity.critter.plugins.RichDisplayBar light1;
    private org.rlcommunity.critter.plugins.RichDisplayBar light2;
    private org.rlcommunity.critter.plugins.RichDisplayBar light3;
    private org.rlcommunity.critter.plugins.RichDisplayBar mcurrent0;
    private org.rlcommunity.critter.plugins.RichDisplayBar mcurrent1;
    private org.rlcommunity.critter.plugins.RichDisplayBar mcurrent2;
    private org.rlcommunity.critter.plugins.RichDisplayBar mspeed0;
    private org.rlcommunity.critter.plugins.RichDisplayBar mspeed1;
    private org.rlcommunity.critter.plugins.RichDisplayBar mspeed2;
    private org.rlcommunity.critter.plugins.RichDisplayBar mtemp0;
    private org.rlcommunity.critter.plugins.RichDisplayBar mtemp1;
    private org.rlcommunity.critter.plugins.RichDisplayBar mtemp2;
    private org.rlcommunity.critter.plugins.RichDisplayBar rotation;
    private javax.swing.JTextField voltage;
    // End of variables declaration//GEN-END:variables
    
}
